/**
 * ISO 3166-1 alpha-2 → ISO numeric (used as feature id in world-atlas topojson)
 * ISO 3166-1 alpha-2 → Italian country name (used in tooltip)
 */

export const alpha2ToNumeric: Record<string, number> = {
  AF: 4,   AX: 248, AL: 8,   DZ: 12,  AS: 16,  AD: 20,  AO: 24,  AI: 660,
  AQ: 10,  AG: 28,  AR: 32,  AM: 51,  AW: 533, AU: 36,  AT: 40,  AZ: 31,
  BS: 44,  BH: 48,  BD: 50,  BB: 52,  BY: 112, BE: 56,  BZ: 84,  BJ: 204,
  BM: 60,  BT: 64,  BO: 68,  BA: 70,  BW: 72,  BR: 76,  BN: 96,  BG: 100,
  BF: 854, BI: 108, CV: 132, KH: 116, CM: 120, CA: 124, CF: 140, TD: 148,
  CL: 152, CN: 156, CO: 170, KM: 174, CG: 178, CD: 180, CR: 188, CI: 384,
  HR: 191, CU: 192, CY: 196, CZ: 203, DK: 208, DJ: 262, DM: 212, DO: 214,
  EC: 218, EG: 818, SV: 222, GQ: 226, ER: 232, EE: 233, SZ: 748, ET: 231,
  FK: 238, FO: 234, FJ: 242, FI: 246, FR: 250, GA: 266, GM: 270, GE: 268,
  DE: 276, GH: 288, GI: 292, GR: 300, GL: 304, GD: 308, GT: 320, GN: 324,
  GW: 624, GY: 328, HT: 332, HN: 340, HU: 348, IS: 352, IN: 356, ID: 360,
  IR: 364, IQ: 368, IE: 372, IL: 376, IT: 380, JM: 388, JP: 392, JO: 400,
  KZ: 398, KE: 404, KI: 296, KP: 408, KR: 410, KW: 414, KG: 417, LA: 418,
  LV: 428, LB: 422, LS: 426, LR: 430, LY: 434, LI: 438, LT: 440, LU: 442,
  MG: 450, MW: 454, MY: 458, MV: 462, ML: 466, MT: 470, MH: 584, MR: 478,
  MU: 480, MX: 484, FM: 583, MD: 498, MC: 492, MN: 496, ME: 499, MA: 504,
  MZ: 508, MM: 104, NA: 516, NR: 520, NP: 524, NL: 528, NC: 540, NZ: 554,
  NI: 558, NE: 562, NG: 566, NO: 578, OM: 512, PK: 586, PW: 585, PS: 275,
  PA: 591, PG: 598, PY: 600, PE: 604, PH: 608, PL: 616, PT: 620, QA: 634,
  RO: 642, RU: 643, RW: 646, KN: 659, LC: 662, VC: 670, WS: 882, SM: 674,
  ST: 678, SA: 682, SN: 686, RS: 688, SC: 690, SL: 694, SG: 702, SK: 703,
  SI: 705, SB: 90,  SO: 706, ZA: 710, SS: 728, ES: 724, LK: 144, SD: 729,
  SR: 740, SE: 752, CH: 756, SY: 760, TW: 158, TJ: 762, TZ: 834, TH: 764,
  TL: 626, TG: 768, TO: 776, TT: 780, TN: 788, TR: 792, TM: 795, TV: 798,
  UG: 800, UA: 804, AE: 784, GB: 826, US: 840, UY: 858, UZ: 860, VU: 548,
  VE: 862, VN: 704, YE: 887, ZM: 894, ZW: 716, MK: 807, XK: 383,
}

export const countryNames: Record<string, string> = {
  AF: 'Afghanistan',      AL: 'Albania',              DZ: 'Algeria',
  AD: 'Andorra',          AO: 'Angola',               AG: 'Antigua e Barbuda',
  AR: 'Argentina',        AM: 'Armenia',              AU: 'Australia',
  AT: 'Austria',          AZ: 'Azerbaigian',          BS: 'Bahamas',
  BH: 'Bahrain',          BD: 'Bangladesh',           BB: 'Barbados',
  BY: 'Bielorussia',      BE: 'Belgio',               BZ: 'Belize',
  BJ: 'Benin',            BT: 'Bhutan',               BO: 'Bolivia',
  BA: 'Bosnia ed Erzegovina', BW: 'Botswana',         BR: 'Brasile',
  BN: 'Brunei',           BG: 'Bulgaria',             BF: 'Burkina Faso',
  BI: 'Burundi',          CV: 'Capo Verde',           KH: 'Cambogia',
  CM: 'Camerun',          CA: 'Canada',               CF: 'Rep. Centrafricana',
  TD: 'Ciad',             CL: 'Cile',                 CN: 'Cina',
  CO: 'Colombia',         KM: 'Comore',               CG: 'Rep. del Congo',
  CD: 'Dem. Rep. Congo',  CR: 'Costa Rica',           CI: "Costa d'Avorio",
  HR: 'Croazia',          CU: 'Cuba',                 CY: 'Cipro',
  CZ: 'Repubblica Ceca',  DK: 'Danimarca',            DJ: 'Gibuti',
  DM: 'Dominica',         DO: 'Rep. Dominicana',      EC: 'Ecuador',
  EG: 'Egitto',           SV: 'El Salvador',          GQ: 'Guinea Equatoriale',
  ER: 'Eritrea',          EE: 'Estonia',              SZ: 'Eswatini',
  ET: 'Etiopia',          FJ: 'Figi',                 FI: 'Finlandia',
  FR: 'Francia',          GA: 'Gabon',                GM: 'Gambia',
  GE: 'Georgia',          DE: 'Germania',             GH: 'Ghana',
  GR: 'Grecia',           GL: 'Groenlandia',          GD: 'Grenada',
  GT: 'Guatemala',        GN: 'Guinea',               GW: 'Guinea-Bissau',
  GY: 'Guyana',           HT: 'Haiti',                HN: 'Honduras',
  HU: 'Ungheria',         IS: 'Islanda',              IN: 'India',
  ID: 'Indonesia',        IR: 'Iran',                 IQ: 'Iraq',
  IE: 'Irlanda',          IL: 'Israele',              IT: 'Italia',
  JM: 'Giamaica',         JP: 'Giappone',             JO: 'Giordania',
  KZ: 'Kazakhstan',       KE: 'Kenya',                KI: 'Kiribati',
  KP: 'Corea del Nord',   KR: 'Corea del Sud',        KW: 'Kuwait',
  KG: 'Kirghizistan',     LA: 'Laos',                 LV: 'Lettonia',
  LB: 'Libano',           LS: 'Lesotho',              LR: 'Liberia',
  LY: 'Libia',            LI: 'Liechtenstein',        LT: 'Lituania',
  LU: 'Lussemburgo',      MG: 'Madagascar',           MW: 'Malawi',
  MY: 'Malaysia',         MV: 'Maldive',              ML: 'Mali',
  MT: 'Malta',            MH: 'Isole Marshall',       MR: 'Mauritania',
  MU: 'Mauritius',        MX: 'Messico',              FM: 'Micronesia',
  MD: 'Moldavia',         MC: 'Monaco',               MN: 'Mongolia',
  ME: 'Montenegro',       MA: 'Marocco',              MZ: 'Mozambico',
  MM: 'Myanmar',          NA: 'Namibia',              NR: 'Nauru',
  NP: 'Nepal',            NL: 'Paesi Bassi',          NZ: 'Nuova Zelanda',
  NI: 'Nicaragua',        NE: 'Niger',                NG: 'Nigeria',
  NO: 'Norvegia',         OM: 'Oman',                 PK: 'Pakistan',
  PW: 'Palau',            PS: 'Palestina',            PA: 'Panama',
  PG: 'Papua Nuova Guinea', PY: 'Paraguay',           PE: 'Perù',
  PH: 'Filippine',        PL: 'Polonia',              PT: 'Portogallo',
  QA: 'Qatar',            RO: 'Romania',              RU: 'Russia',
  RW: 'Ruanda',           KN: 'Saint Kitts e Nevis',  LC: 'Saint Lucia',
  VC: 'Saint Vincent',    WS: 'Samoa',                SM: 'San Marino',
  ST: 'São Tomé e Príncipe', SA: 'Arabia Saudita',    SN: 'Senegal',
  RS: 'Serbia',           SC: 'Seychelles',           SL: 'Sierra Leone',
  SG: 'Singapore',        SK: 'Slovacchia',           SI: 'Slovenia',
  SB: 'Isole Salomone',   SO: 'Somalia',              ZA: 'Sudafrica',
  SS: 'Sudan del Sud',    ES: 'Spagna',               LK: 'Sri Lanka',
  SD: 'Sudan',            SR: 'Suriname',             SE: 'Svezia',
  CH: 'Svizzera',         SY: 'Siria',                TW: 'Taiwan',
  TJ: 'Tagikistan',       TZ: 'Tanzania',             TH: 'Tailandia',
  TL: 'Timor-Leste',      TG: 'Togo',                 TO: 'Tonga',
  TT: 'Trinidad e Tobago', TN: 'Tunisia',             TR: 'Turchia',
  TM: 'Turkmenistan',     TV: 'Tuvalu',               UG: 'Uganda',
  UA: 'Ucraina',          AE: 'Emirati Arabi Uniti',  GB: 'Regno Unito',
  US: 'Stati Uniti',      UY: 'Uruguay',              UZ: 'Uzbekistan',
  VU: 'Vanuatu',          VE: 'Venezuela',            VN: 'Vietnam',
  YE: 'Yemen',            ZM: 'Zambia',               ZW: 'Zimbabwe',
  MK: 'Macedonia del Nord', XK: 'Kosovo',
}

/** Reverse map: ISO numeric → alpha-2 */
export const numericToAlpha2: Record<string, string> = Object.fromEntries(
  Object.entries(alpha2ToNumeric).map(([a2, num]) => [String(num), a2]),
)
